<script setup lang="ts">
// Static counterpart of DepartmentsView. Cards and tabs mirror the real
// directory surface while members remain presentation-only demo data.
import { Building2, Crown, Plus, Users, UsersRound } from "lucide-vue-next";
import { DEMO_COMPANY, DEMO_DEPARTMENTS, DEMO_PEOPLE, DEMO_TEAMS } from "../demoWorkspace";
</script>

<template>
  <div class="flex h-full flex-col overflow-hidden">
    <div class="flex shrink-0 items-center gap-2 border-b px-4 py-2.5 wr-line"><div><h3 class="text-[15px] font-bold tracking-tight wr-t1">Departments &amp; Teams</h3><p class="text-[10px] wr-t3">{{ DEMO_COMPANY.name }} · {{ DEMO_COMPANY.memberCount }} members</p></div><span class="flex-1" /><span class="flex items-center gap-1 rounded-md px-2.5 py-1 text-[10.5px] font-semibold text-white" style="background: linear-gradient(135deg, hsl(var(--wr-lp-brand)), hsl(var(--wr-lp-accent)))"><Plus class="h-3 w-3" /> Add department</span></div>
    <div class="flex shrink-0 items-center gap-1 border-b px-4 pt-2 text-[10.5px] wr-line"><span class="border-b-2 px-1 pb-2 font-semibold" style="border-color: hsl(var(--wr-lp-brand)); color: hsl(var(--wr-lp-brand))"><Building2 class="mr-1 inline h-3 w-3" />Departments</span><span class="px-1 pb-2 wr-t3"><UsersRound class="mr-1 inline h-3 w-3" />Teams</span><span class="ml-auto rounded-md border px-2 py-1 wr-t3 wr-line">Search directory</span></div>

    <div class="min-h-0 flex-1 overflow-hidden p-3"><div class="grid gap-2.5 sm:grid-cols-2 lg:grid-cols-3">
      <article v-for="department in DEMO_DEPARTMENTS" :key="department.id" class="rounded-2xl border p-3 shadow-sm transition hover:shadow-md wr-line-soft" :class="department.name === 'Design' ? 'ring-1 ring-[hsl(var(--wr-lp-brand)/.35)]' : ''" style="background: hsl(var(--wr-lp-app) / .76)"><div class="flex items-start justify-between gap-2"><div class="flex min-w-0 items-center gap-2"><span class="flex h-7 w-7 shrink-0 items-center justify-center rounded-lg" style="background: hsl(var(--wr-lp-brand) / .10)"><Building2 class="h-3.5 w-3.5" style="color: hsl(var(--wr-lp-brand))" /></span><p class="truncate text-[11.5px] font-semibold wr-t1">{{ department.name }}</p></div><span class="flex shrink-0 items-center gap-1 rounded-full bg-black/[.04] px-1.5 py-0.5 text-[9px] wr-t2 dark:bg-white/[.06]"><Users class="h-3 w-3" />{{ department.members }}</span></div><p class="mt-2 line-clamp-2 text-[10px] leading-relaxed wr-t2">{{ department.description }}</p><p class="mt-3 flex items-center gap-1.5 text-[10px] wr-t3"><Crown class="h-3 w-3" />{{ department.lead }}</p><div class="mt-3 flex -space-x-1.5"><span v-for="person in DEMO_PEOPLE.filter((p) => p.department === department.name).slice(0, 4)" :key="person.name" class="flex h-6 w-6 items-center justify-center rounded-full border-2 text-[8px] font-bold text-white" style="background: linear-gradient(135deg, hsl(var(--wr-lp-brand)), hsl(var(--wr-lp-accent))); border-color: hsl(var(--wr-lp-app)">{{ person.initials }}</span></div></article>
    </div>

    <div class="mt-3 rounded-2xl border p-3 wr-app-well wr-line-soft"><div class="mb-2 flex items-center justify-between"><p class="text-[11px] font-semibold wr-t1">Teams</p><span class="text-[9.5px] wr-t3">Cross-department groups</span></div><div class="grid gap-2 sm:grid-cols-2"><div v-for="team in DEMO_TEAMS" :key="team.name" class="rounded-xl border p-2.5 wr-line-soft" style="background: hsl(var(--wr-lp-app))"><div class="flex items-center justify-between gap-2"><span class="truncate text-[10.5px] font-semibold wr-t1">{{ team.name }}</span><span class="text-[9px] wr-t3">{{ team.members.length }} members</span></div><p class="mt-1 text-[9.5px] leading-snug wr-t2">{{ team.description }}</p><p class="mt-2 text-[9px] wr-t3">Lead · {{ team.lead }}</p></div></div></div></div>
  </div>
</template>
